name: ci


env:
  VERSION: v0.893

on:
  push:
    branches: 
      - feature/docker-image

jobs: 
  build-and-publish-head:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: zipline_docker # Provide Docker image name
          image-tag: head # Provide Docker image tag
          build-context: .devcontainer  
